version: "3.8"

services:
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - 8000:8000